# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uid_generator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_gen_import@@

_sym_db = _symbol_database.Default()





DESCRIPTOR = _descriptor.FileDescriptor(
  name='uid_generator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11uid_generator.proto\"\x1e\n\x0cuid_generator\x12\x0e\n\x06saturn_\x18\x01 \x01(\x03\x12\x0e\n\x06garena\x18\x02 \x01(\x03')
)





_UID_GENERATOR = _descriptor.Descriptor(
  name='uid_generator',
  full_name='uid_generator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='saturn_', full_name='uid_generator.saturn_', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='garena', full_name='uid_generator.garena', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['uid_generator'] = _UID_GENERATOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

uid_generator = _reflection.GeneratedProtocolMessageType('uid_generator', (_message.Message,), dict(
  DESCRIPTOR = _UID_GENERATOR,
  __module__ = 'uid_generator_pb2'
  # @@protoc_gen_register@@
  ))
_sym_db.RegisterMessage(uid_generator)
