name: Refresh Spam Tokens

on:
  schedule:
    - cron: '0 */7 * * *' # every 7 hours
  workflow_dispatch: {}

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: TCP+SPAM/spam friend

      - name: Refresh tokens
        run: |
          python - <<'PY'
          import json, requests, sys
          import pathlib
          INPUT = pathlib.Path('TCP+SPAM/spam friend/input_bd.json')
          TOKENS = pathlib.Path('TCP+SPAM/spam friend/token_bd.json')
          URL = 'https://tcp1-two.vercel.app/jwt/cloudgen_jwt'
          data = json.loads(INPUT.read_text(encoding='utf-8'))
          r = requests.post(URL, json=data, headers={'Content-Type':'application/json'}, timeout=300)
          r.raise_for_status()
          items = r.json()
          live = [ {'token': it['token']} for it in items if it.get('status') == 'live' and it.get('token') ]
          if not live:
            print('No live tokens returned; aborting commit')
            sys.exit(1)
          TOKENS.write_text(json.dumps(live, indent=4, ensure_ascii=False), encoding='utf-8')
          print(f'Wrote {len(live)} tokens to', TOKENS)
          PY

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add "TCP+SPAM/spam friend/token_bd.json"
          git commit -m "chore: refresh token_bd.json (scheduled)" || echo "No changes"
          git push

